---
kind: Service
apiVersion: v1
metadata:
  name: remote-terminal
  labels:
    service: remote-terminal
spec:
  ports:
  - name: '80'
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    service: remote-terminal
  type  : LoadBalancer

