---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: remote-terminal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: remote-terminal
    spec:
      restartPolicy: Always
      containers:
      - name: remote-terminal
        image: docker.io/akopper/kubernetes-gotty:latest
        imagePullPolicy: Always
        env:
        - name: BASIC_AUTH_USER
          value: user
        - name: BASIC_AUTH_PASS
          value: pass
  strategy: {}
status: {}
